In [9]:
def generate_increasing_matrix(M, N, start=1, step=1):
    return np.fromfunction(lambda i, j: start + step * (i + j), (M, N), dtype=int)

In [13]:
import numpy as np
import random

def generate_positive_matrix(M_range, N_range, max_value=100):
    # Randomly select M and N within the specified ranges
    M = random.randint(*M_range)
    N = random.randint(*N_range)

    matrix = np.random.randint(1, max_value + 1, size=(M, N))

    start = random.randint(1, 100)

    m1 = generate_increasing_matrix(M, N, start)

    # Generate the matrix with random positive numbers

    return matrix, m1, m1[::-1, ::-1]


generated_matrix = generate_positive_matrix((0, 20), (0, 20))
for g in generated_matrix:
  print(g.shape, g)


(19, 11) [[ 60  38  42  90   9  32  32  21  95  58   8]
 [ 96  72  95  29   7   3  90  18  90   7  63]
 [ 24  68  75  54  26   4  24  93   6  48  19]
 [ 21  79  39  76  90  16  26  65  18  24  62]
 [  3  28  30  29   5  99  37  89   5  48  53]
 [  9  50  63  27  81  69  48 100  91  19  33]
 [ 78  71  60  92  14  89  32  29  61  86  24]
 [ 47   5  64  12   6  50  66  54  59   6  26]
 [ 63  46  57  11  41  93  36  45  31  95  41]
 [ 88  86 100  98  26  17  60  96  33  61  46]
 [  7  47  20  21  11  15  24  49  22  87  73]
 [ 57  13  81  79  59  25  21  98  26  32  70]
 [ 49  60  36  35  98  11  17  30   6  36  51]
 [ 22  18  22  42  10  91  95  15  80  48  64]
 [ 57  29  85  17  17  66  29  53  13  19  58]
 [ 59  25  70  76  45  80  25  27  82  67  81]
 [ 44 100  76  67  53  95  90  57  56  96  78]
 [ 47  61  37   9  72  71  63  33  99  66  75]
 [ 10  73  67  72  50  85  36  18  31  96  62]]
(19, 11) [[ 1  2  3  4  5  6  7  8  9 10 11]
 [ 2  3  4  5  6  7  8  9 10 11 12]
 [ 3  4  5  6  7

In [14]:
type(generated_matrix[0])

numpy.ndarray

In [15]:
mat = generated_matrix[0].tolist()

In [16]:
type(mat)

list

In [17]:
def mass_Gen_positiveMatrices(n):
  ls = []
  for i in range(n):
    for l in generate_positive_matrix((1, 100), (1, 100)):
      ls.append(l)
  return ls

L = mass_Gen_positiveMatrices(20)
L

[array([[ 2, 14, 23, ..., 27, 45, 76],
        [66, 61, 87, ..., 53, 37, 71],
        [60, 43, 98, ..., 81, 70, 93],
        ...,
        [20, 32, 77, ..., 39, 49, 38],
        [24, 11, 80, ..., 89, 39, 18],
        [90, 49, 40, ..., 39, 25, 48]]),
 array([[ 57,  58,  59, ..., 116, 117, 118],
        [ 58,  59,  60, ..., 117, 118, 119],
        [ 59,  60,  61, ..., 118, 119, 120],
        ...,
        [107, 108, 109, ..., 166, 167, 168],
        [108, 109, 110, ..., 167, 168, 169],
        [109, 110, 111, ..., 168, 169, 170]]),
 array([[170, 169, 168, ..., 111, 110, 109],
        [169, 168, 167, ..., 110, 109, 108],
        [168, 167, 166, ..., 109, 108, 107],
        ...,
        [120, 119, 118, ...,  61,  60,  59],
        [119, 118, 117, ...,  60,  59,  58],
        [118, 117, 116, ...,  59,  58,  57]]),
 array([[72, 73, 13],
        [71, 45, 98],
        [47,  8, 73],
        [70, 54, 40],
        [78, 46, 72],
        [38, 32, 32],
        [69, 28,  6]]),
 array([[72, 73, 74],
   

In [18]:
def manipulate_matrix(matrix, percent_zeros=0, percent_negatives=0, shuffle=False):
    manipulated_matrix = matrix.copy()
    total_elements = manipulated_matrix.size

    num_zeros = int(total_elements * percent_zeros / 100)
    zero_indices = np.random.choice(range(total_elements), num_zeros, replace=False)
    np.put(manipulated_matrix, zero_indices, 0)

    non_zero_indices = np.where(manipulated_matrix != 0)[0]
    num_negatives = int(len(non_zero_indices) * percent_negatives / 100)
    negative_indices = np.random.choice(non_zero_indices, num_negatives, replace=False)
    np.put(manipulated_matrix, negative_indices, -np.abs(manipulated_matrix[negative_indices]))

    if shuffle:
        np.random.shuffle(manipulated_matrix)

    return manipulated_matrix

def generate_manipulated_matrices(matrix):
  result = []

  result.append(-np.abs(matrix)) #fully_negative_matrix

  percentiles = [10, 25, 50, 75, 90]

  for p in percentiles:
    result.append(manipulate_matrix(matrix, percent_zeros=p)) #zeros_matrices
    result.append(manipulate_matrix(matrix, percent_zeros=p, shuffle=True)) #shuffled_zeros_matrices
    result.append(manipulate_matrix(matrix, percent_negatives=p)) #negatives_matrices
    result.append(manipulate_matrix(matrix, percent_negatives=p, shuffle=True)) #shuffled_negatives_matrices

    for p2 in percentiles:
      result.append(manipulate_matrix(matrix, percent_zeros=p, percent_negatives=p2)) #combined_matrices
      result.append(manipulate_matrix(matrix, percent_zeros=10, percent_negatives=25, shuffle=True)) #shuffled_combined_matrices

  return result


In [19]:
def mass_Gen_TestCaseMatrices(ls):
  c = []
  for el in ls:
    temp = generate_manipulated_matrices(el)
    for t in temp:
      c.append(t)

  return c

grab = mass_Gen_TestCaseMatrices(L)
print(grab[0], len(grab))

[[ -2 -14 -23 ... -27 -45 -76]
 [-66 -61 -87 ... -53 -37 -71]
 [-60 -43 -98 ... -81 -70 -93]
 ...
 [-20 -32 -77 ... -39 -49 -38]
 [-24 -11 -80 ... -89 -39 -18]
 [-90 -49 -40 ... -39 -25 -48]] 4260


In [20]:
def efficient_reduce_matrices_list(matrices, target_length):
    if len(matrices) <= target_length:
        return matrices

    # Calculate variance for each matrix
    variances = [(i, np.var(matrix)) for i, matrix in enumerate(matrices)]

    # Sort by variance and select the top matrices
    variances.sort(key=lambda x: x[1], reverse=True)
    selected_indices = [i for i, _ in variances[:target_length]]

    # Return the list of matrices with the highest variances
    return [matrices[i] for i in selected_indices]

reduced_matrices = efficient_reduce_matrices_list(grab, 100)

In [21]:
def sort_matrices_by_size(matrices):
    return sorted(matrices, key=lambda x: x.shape[0] * x.shape[1])

sorted_matrices = sort_matrices_by_size(reduced_matrices)
print(sorted_matrices[0])

[[-113  -94 -109   99]
 [ 109  110  111  112]
 [ 103  104  105  106]
 [ 110  111  112  113]
 [ 106  107  108  109]
 [ -95 -112 -114 -110]
 [ 101  102  103  104]
 [-113  -93 -102 -100]
 [-109 -107 -113 -112]
 [ 100  101  102  103]
 [ 105  106  107  108]
 [  98   99  100  101]
 [ 113  114  115  116]
 [  97   98   99  100]
 [ 112  113  114  115]
 [ 104  105  106  107]
 [-114  -98 -116 -115]
 [ 102  103  104  105]
 [-114 -113  -94  -97]
 [ 111  112  113  114]
 [ 107  108  109  110]
 [ 108  109  110  111]
 [  99  100  101  102]]


In [22]:
len(sorted_matrices)

100

In [23]:
def maxMatrixSum_non_constraint(matrix):
    rows = len(matrix)
    cols = len(matrix[0])

    # Calculate cumulative sums
    cumulative_sums = [[0] * (cols + 1) for _ in range(rows + 1)]
    for i in range(1, rows + 1):
        for j in range(1, cols + 1):
            cumulative_sums[i][j] = (
                matrix[i - 1][j - 1]
                + cumulative_sums[i - 1][j]
                + cumulative_sums[i][j - 1]
                - cumulative_sums[i - 1][j - 1]
            )

    max_sum = float('-inf')
    top, left, bottom, right = 0, 0, 0, 0

    # Calculate submatrix sums using cumulative sums
    for i1 in range(1, rows + 1):
        for j1 in range(1, cols + 1):
            for i2 in range(i1, rows + 1):
                for j2 in range(j1, cols + 1):
                    submatrix_sum = (
                        cumulative_sums[i2][j2]
                        - cumulative_sums[i1 - 1][j2]
                        - cumulative_sums[i2][j1 - 1]
                        + cumulative_sums[i1 - 1][j1 - 1]
                    )

                    if submatrix_sum > max_sum:
                        max_sum = submatrix_sum
                        top = i1 - 1
                        left = j1 - 1
                        bottom = i2 - 1
                        right = j2 - 1
                        top_left = (top, left)
                        bottom_right = (bottom, right)
    return max_sum,top_left,bottom_right


def maxMatrixSum_constraint(matrix, K, L):
    rows = len(matrix)
    cols = len(matrix[0])

    # Calculate cumulative sums
    cumulative_sums = [[0] * (cols + 1) for _ in range(rows + 1)]
    for i in range(1, rows + 1):
        for j in range(1, cols + 1):
            cumulative_sums[i][j] = (
                matrix[i - 1][j - 1]
                + cumulative_sums[i - 1][j]
                + cumulative_sums[i][j - 1]
                - cumulative_sums[i - 1][j - 1]
            )

    max_sum = float('-inf')
    top, left, bottom, right = 0, 0, 0, 0

    # Calculate submatrix sums using cumulative sums
    for i in range(K, rows + 1):
        for j in range(L, cols + 1):
            submatrix_sum = (
                cumulative_sums[i][j]
                - cumulative_sums[i - K][j]
                - cumulative_sums[i][j - L]
                + cumulative_sums[i - K][j - L]
            )

            if submatrix_sum > max_sum:
                max_sum = submatrix_sum
                top = i - K
                bottom = i - 1
                left = j - L
                right = j - 1
    return max_sum,(top,left),(bottom,right)

In [24]:
def generate_noncon_Dict(Lmat):
  ls = []
  for m in Lmat:
    dict = {}
    max_sum, top_left, bottom_right = maxMatrixSum_non_constraint(m)
    dict['matrix'] = m.tolist()
    dict["expected_result"] = max_sum
    dict["subarray_indices"] = [top_left, bottom_right]

    ls.append(dict)
  return ls

Constrained_Sols = generate_noncon_Dict(sorted_matrices)

In [25]:
Constrained_Sols

[{'matrix': [[-113, -94, -109, 99],
   [109, 110, 111, 112],
   [103, 104, 105, 106],
   [110, 111, 112, 113],
   [106, 107, 108, 109],
   [-95, -112, -114, -110],
   [101, 102, 103, 104],
   [-113, -93, -102, -100],
   [-109, -107, -113, -112],
   [100, 101, 102, 103],
   [105, 106, 107, 108],
   [98, 99, 100, 101],
   [113, 114, 115, 116],
   [97, 98, 99, 100],
   [112, 113, 114, 115],
   [104, 105, 106, 107],
   [-114, -98, -116, -115],
   [102, 103, 104, 105],
   [-114, -113, -94, -97],
   [111, 112, 113, 114],
   [107, 108, 109, 110],
   [108, 109, 110, 111],
   [99, 100, 101, 102]],
  'expected_result': 5101,
  'subarray_indices': [(1, 0), (22, 3)]},
 {'matrix': [[97, 98, 99, 100],
   [100, 101, 102, 103],
   [109, 110, 111, 112],
   [105, 106, 107, 108],
   [-110, -95, -107, -107],
   [104, 105, 106, 107],
   [99, 100, 101, 102],
   [102, 103, 104, 105],
   [111, 112, 113, 114],
   [-108, -113, -91, -112],
   [98, 99, 100, 101],
   [103, 104, 105, 106],
   [108, 109, 110, 111],


In [26]:
def save_list_to_file(lst, filename):
    with open(filename, 'w') as file:
        for item in lst:
            file.write(f"{item}\n")

save_list_to_file(Constrained_Sols, 'constrainedtestcases.txt')

In [27]:
def save_variable_to_py(variable, variable_name, filename):
    # Convert the variable to a string representation
    variable_str = repr(variable)

    # Create the content to be written to the file
    file_content = f"{variable_name} = {variable_str}\n"

    # Write the content to the file
    with open(filename, 'w') as file:
        file.write(file_content)

# Example usage
save_variable_to_py(Constrained_Sols, 'constrainedtestcases', 'constrainedtestcases.py')

In [28]:
def generate_noncon_Dict(Lmat):
  ls = []
  for m in Lmat:
    dict = {}
    max_sum, top_left, bottom_right = maxMatrixSum_constraint(m, 4, 5)
    dict['matrix'] = m.tolist()
    dict["expected_result"] = max_sum
    dict["subarray_indices"] = [top_left, bottom_right]
    dict["constraints"] = (4,5)

    ls.append(dict)
  return ls

Fixed_KL_Constrained_Sols = generate_noncon_Dict(sorted_matrices)

In [29]:
Fixed_KL_Constrained_Sols

[{'matrix': [[-113, -94, -109, 99],
   [109, 110, 111, 112],
   [103, 104, 105, 106],
   [110, 111, 112, 113],
   [106, 107, 108, 109],
   [-95, -112, -114, -110],
   [101, 102, 103, 104],
   [-113, -93, -102, -100],
   [-109, -107, -113, -112],
   [100, 101, 102, 103],
   [105, 106, 107, 108],
   [98, 99, 100, 101],
   [113, 114, 115, 116],
   [97, 98, 99, 100],
   [112, 113, 114, 115],
   [104, 105, 106, 107],
   [-114, -98, -116, -115],
   [102, 103, 104, 105],
   [-114, -113, -94, -97],
   [111, 112, 113, 114],
   [107, 108, 109, 110],
   [108, 109, 110, 111],
   [99, 100, 101, 102]],
  'expected_result': -inf,
  'subarray_indices': [(0, 0), (0, 0)],
  'constraints': (4, 5)},
 {'matrix': [[97, 98, 99, 100],
   [100, 101, 102, 103],
   [109, 110, 111, 112],
   [105, 106, 107, 108],
   [-110, -95, -107, -107],
   [104, 105, 106, 107],
   [99, 100, 101, 102],
   [102, 103, 104, 105],
   [111, 112, 113, 114],
   [-108, -113, -91, -112],
   [98, 99, 100, 101],
   [103, 104, 105, 106],
 

In [30]:
save_variable_to_py(Fixed_KL_Constrained_Sols, 'fixedtextcases', 'fixedtestcases.py')

In [32]:
def find_median_matrix(matrices):
    median_matrix = matrices[int(len(matrices)/2)]
    return median_matrix

median_matrix = find_median_matrix(sorted_matrices)
print(median_matrix.shape, median_matrix)

(82, 7) [[ 151  150    0  148  147  146  145]
 [ 118  117  116  115  114  113    0]
 [ 141  140  139  138  137  136  135]
 [ 105  104  103  102  101    0   99]
 [ 159  158  157    0  155  154    0]
 [ 100   99   98   97   96   95   94]
 [ 111  110  109  108    0  106  105]
 [ 166    0  164  163  162  161  160]
 [-148  -96 -168  167  -99    0  164]
 [ 134  133  132    0  130  129  128]
 [ 162  161  160  159  158  157  156]
 [ 149  148  147  146  145  144    0]
 [ 150    0  148  147  146  145    0]
 [ 104  103  102    0  100   99   98]
 [-169  173 -110    0 -142 -163  168]
 [ 161  160  159  158  157  156  155]
 [-110 -154  176 -166 -136 -165    0]
 [ 136  135  134  133  132  131  130]
 [ 158  157  156  155  154  153  152]
 [ 115  114  113  112  111  110  109]
 [ 109  108  107  106    0  104  103]
 [ 137  136  135  134  133  132  131]
 [ 103  102    0  100   99   98   97]
 [ 164  163  162  161  160  159  158]
 [ 171 -150 -175  168 -173 -147 -169]
 [   0    0  128  127  126  125  124]
 [ 1

In [34]:
import numpy as np

def generate_rectangular_matrix(M, N):
    # Randomly generate numbers in the range [-100, 100]
    matrix = np.random.randint(-100, 101, size=(M, N))
    return matrix

# Generate a 20x20 matrix
rectangular_matrix = generate_rectangular_matrix(10, 10)
print(rectangular_matrix)


[[ 83  -6 -80 -78  -9 -99 -85  96   8 -53]
 [ 64  87 -55  51 -71  43 -29  40   0   9]
 [ 85 -66  50  99 -87  58  40  92 -81  78]
 [ 87  67 -30  16 -44  61 -90 -94  29  -8]
 [ 41  37  12  92 -81  26 -51 -41  71  12]
 [ -4 -84  58  -1  23 -38  86 -24 -72  90]
 [ 21 -78  83 -97  56   0 -86 -32  20  96]
 [ 59 -96  75 -47 -97  70 -98  92  90  62]
 [ 59  64  12 -45  96  98  90  66 -96   6]
 [-29 -50  88  94  91 -74  34  11 100  35]]


In [35]:
import numpy as np

def generate_submatrix_tuples(matrix, max_k, max_l):
    tuples = []
    M, N = matrix.shape

    for K in range(1, min(M, max_k) + 1):
        for L in range(1, min(N, max_l) + 1):
            tuples.append((matrix, (K, L)))

    return tuples

def sort_tuples_by_submatrix_size(tuples):
    """
    Sort the list of tuples by the size of the submatrix (K * L).
    """
    return sorted(tuples, key=lambda x: x[1][0] * x[1][1])


# Generate and sort the tuples
submatrix_tuples = generate_submatrix_tuples(rectangular_matrix, int(rectangular_matrix.shape[0]/2), int(rectangular_matrix.shape[1]/2))
sorted_tuples = sort_tuples_by_submatrix_size(submatrix_tuples)

# You can now work with sorted_tuples which are sorted by submatrix sizes (K * L)
sorted_tuples

[(array([[ 83,  -6, -80, -78,  -9, -99, -85,  96,   8, -53],
         [ 64,  87, -55,  51, -71,  43, -29,  40,   0,   9],
         [ 85, -66,  50,  99, -87,  58,  40,  92, -81,  78],
         [ 87,  67, -30,  16, -44,  61, -90, -94,  29,  -8],
         [ 41,  37,  12,  92, -81,  26, -51, -41,  71,  12],
         [ -4, -84,  58,  -1,  23, -38,  86, -24, -72,  90],
         [ 21, -78,  83, -97,  56,   0, -86, -32,  20,  96],
         [ 59, -96,  75, -47, -97,  70, -98,  92,  90,  62],
         [ 59,  64,  12, -45,  96,  98,  90,  66, -96,   6],
         [-29, -50,  88,  94,  91, -74,  34,  11, 100,  35]]),
  (1, 1)),
 (array([[ 83,  -6, -80, -78,  -9, -99, -85,  96,   8, -53],
         [ 64,  87, -55,  51, -71,  43, -29,  40,   0,   9],
         [ 85, -66,  50,  99, -87,  58,  40,  92, -81,  78],
         [ 87,  67, -30,  16, -44,  61, -90, -94,  29,  -8],
         [ 41,  37,  12,  92, -81,  26, -51, -41,  71,  12],
         [ -4, -84,  58,  -1,  23, -38,  86, -24, -72,  90],
         [ 

In [39]:
print(sorted_tuples[0])

(array([[ 83,  -6, -80, -78,  -9, -99, -85,  96,   8, -53],
       [ 64,  87, -55,  51, -71,  43, -29,  40,   0,   9],
       [ 85, -66,  50,  99, -87,  58,  40,  92, -81,  78],
       [ 87,  67, -30,  16, -44,  61, -90, -94,  29,  -8],
       [ 41,  37,  12,  92, -81,  26, -51, -41,  71,  12],
       [ -4, -84,  58,  -1,  23, -38,  86, -24, -72,  90],
       [ 21, -78,  83, -97,  56,   0, -86, -32,  20,  96],
       [ 59, -96,  75, -47, -97,  70, -98,  92,  90,  62],
       [ 59,  64,  12, -45,  96,  98,  90,  66, -96,   6],
       [-29, -50,  88,  94,  91, -74,  34,  11, 100,  35]]), (1, 1))


In [41]:
def generate_noncon_Dict(Lmat):
  ls = []
  for m,c  in Lmat:

    dict = {}
    max_sum, top_left, bottom_right = maxMatrixSum_constraint(m, c[0], c[1])
    dict['matrix'] = m.tolist()
    dict["expected_result"] = max_sum
    dict["subarray_indices"] = [top_left, bottom_right]
    dict["constraints"] = c

    ls.append(dict)
  return ls

Variable_Constrained_Sols = generate_noncon_Dict(sorted_tuples)

In [42]:
Variable_Constrained_Sols

[{'matrix': [[83, -6, -80, -78, -9, -99, -85, 96, 8, -53],
   [64, 87, -55, 51, -71, 43, -29, 40, 0, 9],
   [85, -66, 50, 99, -87, 58, 40, 92, -81, 78],
   [87, 67, -30, 16, -44, 61, -90, -94, 29, -8],
   [41, 37, 12, 92, -81, 26, -51, -41, 71, 12],
   [-4, -84, 58, -1, 23, -38, 86, -24, -72, 90],
   [21, -78, 83, -97, 56, 0, -86, -32, 20, 96],
   [59, -96, 75, -47, -97, 70, -98, 92, 90, 62],
   [59, 64, 12, -45, 96, 98, 90, 66, -96, 6],
   [-29, -50, 88, 94, 91, -74, 34, 11, 100, 35]],
  'expected_result': 100,
  'subarray_indices': [(9, 8), (9, 8)],
  'constraints': (1, 1)},
 {'matrix': [[83, -6, -80, -78, -9, -99, -85, 96, 8, -53],
   [64, 87, -55, 51, -71, 43, -29, 40, 0, 9],
   [85, -66, 50, 99, -87, 58, 40, 92, -81, 78],
   [87, 67, -30, 16, -44, 61, -90, -94, 29, -8],
   [41, 37, 12, 92, -81, 26, -51, -41, 71, 12],
   [-4, -84, 58, -1, 23, -38, 86, -24, -72, 90],
   [21, -78, 83, -97, 56, 0, -86, -32, 20, 96],
   [59, -96, 75, -47, -97, 70, -98, 92, 90, 62],
   [59, 64, 12, -45,

In [43]:
save_variable_to_py(Variable_Constrained_Sols, 'variableconstrainedtestcases', 'variableconstrainedtestcases.py')