In [23]:
def generate_increasing_matrix(M, N, start=1, step=1):
    return np.fromfunction(lambda i, j: start + step * (i + j), (M, N), dtype=int)

In [24]:
import numpy as np
import random

def generate_positive_matrix(M_range, N_range, max_value=100):
    # Randomly select M and N within the specified ranges
    M = random.randint(*M_range)
    N = random.randint(*N_range)

    matrix = np.random.randint(1, max_value + 1, size=(M, N))

    start = random.randint(1, 100)

    m1 = generate_increasing_matrix(M, N, start)

    # Generate the matrix with random positive numbers

    return matrix, m1, m1[::-1, ::-1]


generated_matrix = generate_positive_matrix((0, 25), (0, 25))
for g in generated_matrix:
  print(g.shape, g)


(19, 2) [[52 30]
 [ 9 13]
 [29 99]
 [ 8 22]
 [71 98]
 [68 93]
 [51 49]
 [23 48]
 [63 53]
 [32 20]
 [12 69]
 [76 11]
 [55 75]
 [23  5]
 [85  7]
 [31 95]
 [24 67]
 [21 74]
 [26 75]]
(19, 2) [[ 89  90]
 [ 90  91]
 [ 91  92]
 [ 92  93]
 [ 93  94]
 [ 94  95]
 [ 95  96]
 [ 96  97]
 [ 97  98]
 [ 98  99]
 [ 99 100]
 [100 101]
 [101 102]
 [102 103]
 [103 104]
 [104 105]
 [105 106]
 [106 107]
 [107 108]]
(19, 2) [[108 107]
 [107 106]
 [106 105]
 [105 104]
 [104 103]
 [103 102]
 [102 101]
 [101 100]
 [100  99]
 [ 99  98]
 [ 98  97]
 [ 97  96]
 [ 96  95]
 [ 95  94]
 [ 94  93]
 [ 93  92]
 [ 92  91]
 [ 91  90]
 [ 90  89]]


In [25]:
def mass_Gen_positiveMatrices(n):
  ls = []
  for i in range(n):
    for l in generate_positive_matrix((1, 100), (1, 100)):
      ls.append(l)
  return ls

L = mass_Gen_positiveMatrices(20)
L

[array([[ 37,   3,  10, ...,  51,  46,  20],
        [ 64,  61,  68, ..., 100,  81,   1],
        [ 15,  81,  84, ...,  92,  41,  70],
        ...,
        [ 68,  99,  46, ...,  53,  70,  95],
        [ 75,  16,  59, ...,  54,  63,  96],
        [  5,   7,  41, ..., 100,  27,  93]]),
 array([[ 82,  83,  84, ..., 162, 163, 164],
        [ 83,  84,  85, ..., 163, 164, 165],
        [ 84,  85,  86, ..., 164, 165, 166],
        ...,
        [ 94,  95,  96, ..., 174, 175, 176],
        [ 95,  96,  97, ..., 175, 176, 177],
        [ 96,  97,  98, ..., 176, 177, 178]]),
 array([[178, 177, 176, ...,  98,  97,  96],
        [177, 176, 175, ...,  97,  96,  95],
        [176, 175, 174, ...,  96,  95,  94],
        ...,
        [166, 165, 164, ...,  86,  85,  84],
        [165, 164, 163, ...,  85,  84,  83],
        [164, 163, 162, ...,  84,  83,  82]]),
 array([[ 94,  25,  69, ...,  83,  73,  27],
        [ 65,  82,  59, ...,  16,  11,  98],
        [ 23,  69,  18, ...,  92,  84,  90],
        ..

In [26]:
def manipulate_matrix(matrix, percent_zeros=0, percent_negatives=0, shuffle=False):
    manipulated_matrix = matrix.copy()
    total_elements = manipulated_matrix.size

    num_zeros = int(total_elements * percent_zeros / 100)
    zero_indices = np.random.choice(range(total_elements), num_zeros, replace=False)
    np.put(manipulated_matrix, zero_indices, 0)

    non_zero_indices = np.where(manipulated_matrix != 0)[0]
    num_negatives = int(len(non_zero_indices) * percent_negatives / 100)
    negative_indices = np.random.choice(non_zero_indices, num_negatives, replace=False)
    np.put(manipulated_matrix, negative_indices, -np.abs(manipulated_matrix[negative_indices]))

    if shuffle:
        np.random.shuffle(manipulated_matrix)

    return manipulated_matrix

def generate_manipulated_matrices(matrix):
  result = []

  result.append(-np.abs(matrix)) #fully_negative_matrix

  percentiles = [10, 25, 50, 75, 90]

  for p in percentiles:
    result.append(manipulate_matrix(matrix, percent_zeros=p)) #zeros_matrices
    result.append(manipulate_matrix(matrix, percent_zeros=p, shuffle=True)) #shuffled_zeros_matrices
    result.append(manipulate_matrix(matrix, percent_negatives=p)) #negatives_matrices
    result.append(manipulate_matrix(matrix, percent_negatives=p, shuffle=True)) #shuffled_negatives_matrices

    for p2 in percentiles:
      result.append(manipulate_matrix(matrix, percent_zeros=p, percent_negatives=p2)) #combined_matrices
      result.append(manipulate_matrix(matrix, percent_zeros=10, percent_negatives=25, shuffle=True)) #shuffled_combined_matrices

  return result


In [27]:
def mass_Gen_TestCaseMatrices(ls):
  c = []
  for el in ls:
    temp = generate_manipulated_matrices(el)
    for t in temp:
      c.append(t)

  return c

grab = mass_Gen_TestCaseMatrices(L)
print(grab[0], len(grab))

[[ -37   -3  -10 ...  -51  -46  -20]
 [ -64  -61  -68 ... -100  -81   -1]
 [ -15  -81  -84 ...  -92  -41  -70]
 ...
 [ -68  -99  -46 ...  -53  -70  -95]
 [ -75  -16  -59 ...  -54  -63  -96]
 [  -5   -7  -41 ... -100  -27  -93]] 4260


In [28]:
def efficient_reduce_matrices_list(matrices, target_length):
    if len(matrices) <= target_length:
        return matrices

    # Calculate variance for each matrix
    variances = [(i, np.var(matrix)) for i, matrix in enumerate(matrices)]

    # Sort by variance and select the top matrices
    variances.sort(key=lambda x: x[1], reverse=True)
    selected_indices = [i for i, _ in variances[:target_length]]

    # Return the list of matrices with the highest variances
    return [matrices[i] for i in selected_indices]

reduced_matrices = efficient_reduce_matrices_list(grab, 100)

In [18]:
def sort_matrices_by_size(matrices):
    return sorted(matrices, key=lambda x: x.shape[0] * x.shape[1])

sorted_matrices = sort_matrices_by_size(reduced_matrices)
print(sorted_matrices[0])

[[-161 -156    0 -165 -162 -169 -168    0   99  100  101  102    0  104
   105  106    0    0  109  110  111    0    0    0    0  116    0  118
     0    0    0    0  123  124    0    0  127    0  129    0    0  132
   133    0    0  136  137    0  139    0  141  142  143  144    0    0
     0  148    0    0  151    0  153  154    0    0  157  158    0    0
   161    0    0  164]
 [   0   93   94   95   96   97   98    0    0    0    0    0  104  105
     0    0    0    0    0  111    0  113    0    0    0    0  118  119
   120  121    0  123  124  125    0    0  128    0    0    0  132    0
     0  135  136    0    0  139    0  141    0  143  144  145    0  147
     0  149    0  151  152    0  154  155  156  157  158    0  160  161
     0    0  164  165]
 [   0   94    0   96   97    0   99  100    0    0  103  104    0  106
   107  108  109  110  111  112    0    0    0  116  117    0    0  120
     0    0  123  124  125    0    0    0    0    0    0  132    0  134
     0    0    0  

In [29]:
len(sorted_matrices)

100

In [30]:
def maxMatrixSum_non_constraint(matrix):
    rows = len(matrix)
    cols = len(matrix[0])

    # Calculate cumulative sums
    cumulative_sums = [[0] * (cols + 1) for _ in range(rows + 1)]
    for i in range(1, rows + 1):
        for j in range(1, cols + 1):
            cumulative_sums[i][j] = (
                matrix[i - 1][j - 1]
                + cumulative_sums[i - 1][j]
                + cumulative_sums[i][j - 1]
                - cumulative_sums[i - 1][j - 1]
            )

    max_sum = float('-inf')
    top, left, bottom, right = 0, 0, 0, 0

    # Calculate submatrix sums using cumulative sums
    for i1 in range(1, rows + 1):
        for j1 in range(1, cols + 1):
            for i2 in range(i1, rows + 1):
                for j2 in range(j1, cols + 1):
                    submatrix_sum = (
                        cumulative_sums[i2][j2]
                        - cumulative_sums[i1 - 1][j2]
                        - cumulative_sums[i2][j1 - 1]
                        + cumulative_sums[i1 - 1][j1 - 1]
                    )

                    if submatrix_sum > max_sum:
                        max_sum = submatrix_sum
                        top = i1 - 1
                        left = j1 - 1
                        bottom = i2 - 1
                        right = j2 - 1
                        top_left = (top, left)
                        bottom_right = (bottom, right)
    return max_sum,top_left,bottom_right


def maxMatrixSum_constraint(matrix, K, L):
    rows = len(matrix)
    cols = len(matrix[0])

    # Calculate cumulative sums
    cumulative_sums = [[0] * (cols + 1) for _ in range(rows + 1)]
    for i in range(1, rows + 1):
        for j in range(1, cols + 1):
            cumulative_sums[i][j] = (
                matrix[i - 1][j - 1]
                + cumulative_sums[i - 1][j]
                + cumulative_sums[i][j - 1]
                - cumulative_sums[i - 1][j - 1]
            )

    max_sum = float('-inf')
    top, left, bottom, right = 0, 0, 0, 0

    # Calculate submatrix sums using cumulative sums
    for i in range(K, rows + 1):
        for j in range(L, cols + 1):
            submatrix_sum = (
                cumulative_sums[i][j]
                - cumulative_sums[i - K][j]
                - cumulative_sums[i][j - L]
                + cumulative_sums[i - K][j - L]
            )

            if submatrix_sum > max_sum:
                max_sum = submatrix_sum
                top = i - K
                bottom = i - 1
                left = j - L
                right = j - 1
    return max_sum,(top,left),(bottom,right)

In [31]:
def generate_noncon_Dict(Lmat):
  ls = []
  for m in Lmat:
    dict = {}
    max_sum, top_left, bottom_right = maxMatrixSum_non_constraint(m)
    dict['matrix'] = m
    dict["expected_result"] = max_sum
    dict["subarray_indices"] = [top_left, bottom_right]

    ls.append(dict)
  return ls

Constrained_Sols = generate_noncon_Dict(sorted_matrices)

In [32]:
Constrained_Sols

[{'matrix': array([[-161, -156,    0, -165, -162, -169, -168,    0,   99,  100,  101,
           102,    0,  104,  105,  106,    0,    0,  109,  110,  111,    0,
             0,    0,    0,  116,    0,  118,    0,    0,    0,    0,  123,
           124,    0,    0,  127,    0,  129,    0,    0,  132,  133,    0,
             0,  136,  137,    0,  139,    0,  141,  142,  143,  144,    0,
             0,    0,  148,    0,    0,  151,    0,  153,  154,    0,    0,
           157,  158,    0,    0,  161,    0,    0,  164],
         [   0,   93,   94,   95,   96,   97,   98,    0,    0,    0,    0,
             0,  104,  105,    0,    0,    0,    0,    0,  111,    0,  113,
             0,    0,    0,    0,  118,  119,  120,  121,    0,  123,  124,
           125,    0,    0,  128,    0,    0,    0,  132,    0,    0,  135,
           136,    0,    0,  139,    0,  141,    0,  143,  144,  145,    0,
           147,    0,  149,    0,  151,  152,    0,  154,  155,  156,  157,
           158,    

In [33]:
def save_list_to_file(lst, filename):
    with open(filename, 'w') as file:
        for item in lst:
            file.write(f"{item}\n")

save_list_to_file(Constrained_Sols, 'constrainedtestcases.txt')

In [35]:
def save_variable_to_py(variable, variable_name, filename):
    # Convert the variable to a string representation
    variable_str = repr(variable)

    # Create the content to be written to the file
    file_content = f"{variable_name} = {variable_str}\n"

    # Write the content to the file
    with open(filename, 'w') as file:
        file.write(file_content)

# Example usage
save_variable_to_py(Constrained_Sols, 'constrainedtestcases', 'constrainedtestcases.py')

In [36]:
def generate_noncon_Dict(Lmat):
  ls = []
  for m in Lmat:
    dict = {}
    max_sum, top_left, bottom_right = maxMatrixSum_constraint(m, 4, 5)
    dict['matrix'] = m
    dict["expected_result"] = max_sum
    dict["subarray_indices"] = [top_left, bottom_right]
    dict["constraints"] = (4,5)

    ls.append(dict)
  return ls

Fixed_KL_Constrained_Sols = generate_noncon_Dict(sorted_matrices)

In [37]:
Fixed_KL_Constrained_Sols

[{'matrix': array([[-161, -156,    0, -165, -162, -169, -168,    0,   99,  100,  101,
           102,    0,  104,  105,  106,    0,    0,  109,  110,  111,    0,
             0,    0,    0,  116,    0,  118,    0,    0,    0,    0,  123,
           124,    0,    0,  127,    0,  129,    0,    0,  132,  133,    0,
             0,  136,  137,    0,  139,    0,  141,  142,  143,  144,    0,
             0,    0,  148,    0,    0,  151,    0,  153,  154,    0,    0,
           157,  158,    0,    0,  161,    0,    0,  164],
         [   0,   93,   94,   95,   96,   97,   98,    0,    0,    0,    0,
             0,  104,  105,    0,    0,    0,    0,    0,  111,    0,  113,
             0,    0,    0,    0,  118,  119,  120,  121,    0,  123,  124,
           125,    0,    0,  128,    0,    0,    0,  132,    0,    0,  135,
           136,    0,    0,  139,    0,  141,    0,  143,  144,  145,    0,
           147,    0,  149,    0,  151,  152,    0,  154,  155,  156,  157,
           158,    

In [39]:
save_variable_to_py(Fixed_KL_Constrained_Sols, 'fixedtextcases', 'fixedtestcases.py')

In [50]:
def find_largest_matrix(matrices):
    largest_matrix = (matrices, key=lambda x: x.shape[0] * x.shape[1])
    return largest_matrix

largest_matrix = find_largest_matrix(sorted_matrices)
print(largest_matrix.shape, largest_matrix)

(71, 99) [[   0    0 -143 ...  159    0    0]
 [  64   65   66 ...    0  161  162]
 [  65   66   67 ...    0  162    0]
 ...
 [ 131  132  133 ...    0    0    0]
 [ 132    0  134 ...    0    0    0]
 [   0  134    0 ...  229    0    0]]


In [53]:
def find_median_matrix(matrices):
    median_matrix = matrices[int(len(matrices)/2)]
    return median_matrix

median_matrix = find_median_matrix(sorted_matrices)
print(median_matrix.shape, median_matrix)

(83, 35) [[   0    0    0 ...    0 -140 -156]
 [   0 -146    0 ...    0 -129 -150]
 [   0    0 -124 ...  117  118  119]
 ...
 [ 163    0  165 ...    0  196  197]
 [   0  165  166 ...  196  197    0]
 [ 165  166    0 ...    0    0    0]]


In [54]:
import numpy as np

def generate_rectangular_matrix(M, N):
    # Randomly generate numbers in the range [-100, 100]
    matrix = np.random.randint(-100, 101, size=(M, N))
    return matrix

# Generate a 20x20 matrix
rectangular_matrix = generate_rectangular_matrix(20, 20)
print(rectangular_matrix)


[[ -92   89   14    2   65   59   -8  -38   18   69   50   79  -77   44
    -9   41   40  -33   92  -95]
 [ -64  -69   -6   -8   30  -75  -65   30   44   31   63  -37   71  100
    80   86  -33   67  -65   68]
 [ -81  -24   57   19   66   68  -71   70   -9   99  -67  -30   21   45
    72  -75   58   87  -73  -68]
 [ -60  -92 -100   61   40   95  -96  -36  -39   57   -7  -68  -80  -54
   -82  -17  -48   -7  -41  -13]
 [ -78  -13  -79  -59  -90  -73  -51  -35  -16  -14  -34   10  -42   15
   -86   42  -77  -29  -10   59]
 [  -7   91   46   54   87  -66  -19   79   43    9   65  -25   53  -37
    89   47   57  -49  -24   73]
 [  21  -41   42   63 -100   55   -8  -10  -42    9   11   39   71   94
    69    0   33   82   58  -62]
 [ -51   38  -19  -23   -3    8  -22  -62  -91   12   76  -54   16  -76
    87  -37   74   -2   58    1]
 [ -23  -15   71   45  -82  -60   31   34   17   83   38   73    3  -78
   -59  -39   93  -91  -23  -96]
 [   9   27  -37   56   12   49   52   27   83   65   9

In [55]:
import numpy as np

def generate_submatrix_tuples(matrix, max_k, max_l):
    tuples = []
    M, N = matrix.shape

    for K in range(1, min(M, max_k) + 1):
        for L in range(1, min(N, max_l) + 1):
            tuples.append((matrix, (K, L)))

    return tuples

def sort_tuples_by_submatrix_size(tuples):
    """
    Sort the list of tuples by the size of the submatrix (K * L).
    """
    return sorted(tuples, key=lambda x: x[1][0] * x[1][1])


# Generate and sort the tuples
submatrix_tuples = generate_submatrix_tuples(rectangular_matrix, int(rectangular_matrix.shape[0]/2), int(rectangular_matrix.shape[1]/2))
sorted_tuples = sort_tuples_by_submatrix_size(submatrix_tuples)

# You can now work with sorted_tuples which are sorted by submatrix sizes (K * L)
sorted_tuples

[(array([[ -92,   89,   14,    2,   65,   59,   -8,  -38,   18,   69,   50,
            79,  -77,   44,   -9,   41,   40,  -33,   92,  -95],
         [ -64,  -69,   -6,   -8,   30,  -75,  -65,   30,   44,   31,   63,
           -37,   71,  100,   80,   86,  -33,   67,  -65,   68],
         [ -81,  -24,   57,   19,   66,   68,  -71,   70,   -9,   99,  -67,
           -30,   21,   45,   72,  -75,   58,   87,  -73,  -68],
         [ -60,  -92, -100,   61,   40,   95,  -96,  -36,  -39,   57,   -7,
           -68,  -80,  -54,  -82,  -17,  -48,   -7,  -41,  -13],
         [ -78,  -13,  -79,  -59,  -90,  -73,  -51,  -35,  -16,  -14,  -34,
            10,  -42,   15,  -86,   42,  -77,  -29,  -10,   59],
         [  -7,   91,   46,   54,   87,  -66,  -19,   79,   43,    9,   65,
           -25,   53,  -37,   89,   47,   57,  -49,  -24,   73],
         [  21,  -41,   42,   63, -100,   55,   -8,  -10,  -42,    9,   11,
            39,   71,   94,   69,    0,   33,   82,   58,  -62],
         [ -5

In [59]:
def generate_noncon_Dict(Lmat):
  ls = []
  for m,c  in Lmat:
    dict = {}
    max_sum, top_left, bottom_right = maxMatrixSum_constraint(m, c[0], c[1])
    dict['matrix'] = m
    dict["expected_result"] = max_sum
    dict["subarray_indices"] = [top_left, bottom_right]
    dict["constraints"] = c

    ls.append(dict)
  return ls

Variable_Constrained_Sols = generate_noncon_Dict(submatrix_tuples)

In [61]:
save_variable_to_py(Variable_Constrained_Sols, 'variabletextcases', 'variabletestcases.py')