In [1]:
import numpy as np
from collections import deque

def sub_mat(A, i1, i2, j1, j2):
    return (A[i1:i2+1, j1:j2+1])

def validity(row, col, i1, i2, j1, j2):
    a = (i1 <= i2) and (j1 <= j2) and (i1 >= 0) and (i2 < row) and (j1 >= 0) and (j1 < col)
    return(a)

def child_node(child):
    row, col, i1, i2, j1, j2 = child
    children = []
    if validity(row, col, i1+1, i2, j1, j2):
        children.append((row, col, i1+1, i2, j1, j2))

    if validity(row, col, i1, i2-1, j1, j2):
        children.append((row, col, i1, i2-1, j1, j2))

    if validity(row, col, i1, i2, j1+1, j2):
        children.append((row, col, i1, i2, j1+1, j2))

    if validity(row, col, i1, i2, j1, j2-1):
        children.append((row, col, i1, i2, j1, j2-1))

    return children

def max_sub_mat(matrix):
    row = len(matrix)
    col = len(matrix[0])
    max_sum = -np.inf
    max_sub_mat = None
    
    q = deque()
    
    q.append((np.sum(matrix), (row, col, 0, row-1, 0, col-1)))
    
    while q:
        _, nod = q.popleft()
        
        if not validity(*nod):
            continue

        nod_sum = np.sum(matrix[nod[2]:nod[3]+1, nod[4]:nod[5]+1])

        if nod_sum > max_sum:
            max_sum = nod_sum
            max_sub_mat = nod
        
        for c in child_node(nod):
            
            c_sum = np.sum(matrix[c[2]:c[3]+1, c[4]:c[5]+1])

            if c_sum > max_sum:
                q.append((c_sum, c)) 
            
    print("Original matrix:\n", matrix)
    print("Largest sum subarray:\n", matrix[max_sub_mat[2]:max_sub_mat[3]+1,max_sub_mat[4]:max_sub_mat[5]+1])
    print("Total sum:", max_sum)
    print("Coordinates (i1,j1), (i2,j2) of the submatrix:", (max_sub_mat[2]+1, max_sub_mat[3]+1), (max_sub_mat[4]+1, max_sub_mat[5]+1))

A = np.array([[1, 2, -1, -4, -20],
              [-8, -3, 4, 2, 1],
              [3, 8, 10, 1, 3],
              [-4, -1, 1, 7, -6]])
max_sub_mat(A)

Original matrix:
 [[  1   2  -1  -4 -20]
 [ -8  -3   4   2   1]
 [  3   8  10   1   3]
 [ -4  -1   1   7  -6]]
Largest sum subarray:
 [[-3  4  2]
 [ 8 10  1]
 [-1  1  7]]
Total sum: 29
Coordinates (i1,j1), (i2,j2) of the submatrix: (2, 4) (2, 4)


C:\Users\annak\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\annak\anaconda3\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\Users\annak\anaconda3\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
